### ISSUE TITLE
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1

### ISSUE THREAD

**Issue by encloinc** [Arinerron/ScratchAPI#33]
I dont know if this is still being worked on or anything but I am getting this error when using the code
_Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
	at edu.mit.scratch.Scratch.createSession(Scratch.java:136)
	at Main.main(Main.java:4)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)_

**Comment by Arinerron** [comment]
Mind sending a snippet of code causing the issue? (be sure to snip out your username/password)

I haven't really been working on this anymore since I was banned, but I'll see if I can help still.

**Comment by Arinerron** [comment]
Nevermind, found the bug. Fixed in commit https://github.com/Arinerron/ScratchAPI/commit/f802550c4600358b4cf8059c741d58416c4f694a.
